start: module

module: symbol*

symbol: struct_def
      | func_def
      | global_def
      | enum_def
      | module_stmt
      | import_stmt

struct_def: "struct" ident "{" struct_field* "}"
func_def: "fn" ident "(" func_param_list? ")" ("->" type)? "{" block "}"
global_def: (CONST | (STATIC mut?)) ident ":" type "=" expr ";"
enum_def: "enum" ident "{" enum_field* "}"
import_stmt: "import" fq_ident ("," fq_ident)* ";"

block: stmt*

?stmt: assign_stmt
     | let_stmt
     | return_stmt
     | expr_stmt
     | for_stmt
     | while_stmt
     | if_stmt
     | break_stmt
     | continue_stmt
     | module_stmt

// namespacing
module_stmt: "module" ident "{" symbol* "}"

// block statements
expr_stmt: expr ";"
assign_stmt: ident assign_op expr ";"
let_stmt: "let" mut? ident (":" type)? "=" expr ";"
for_stmt: "for" ident "in" expr "{" block "}"

// block conditionals
while_stmt: "while" expr "{" block "}"
if_stmt: "if" expr "{" block "}" elif_clause* else_clause?
elif_clause: "else" "if" expr "{" block "}"
else_clause: "else" "{" block "}"

// control flow
break_stmt: "break" ";"
continue_stmt: "continue" ";"
return_stmt: "return" expr? ";"

arg_list: expr ("," expr)* [","]

?expr: logical_or
?logical_or: logical_or "||" logical_and -> or_op
           | logical_and
?logical_and: logical_and "&&" comp -> and_op
            | comp
?comp: comp "==" bit_or -> eq_op
     | comp "!=" bit_or -> ne_op
     | comp ">" bit_or -> gt_op
     | comp "<" bit_or -> lt_op
     | comp "<=" bit_or -> lte_op
     | comp ">=" bit_or -> gte_op
     | bit_or
?bit_or: bit_or "|" bit_xor -> bwor_op
       | bit_xor
?bit_xor: bit_xor "^" bit_and -> bwxor_op
        | bit_and
?bit_and: bit_and "&" shift -> bwand_op
        | shift
?shift: shift "<<" add -> shl_op
      | shift ">>" add -> shr_op
      | add
?add: add "+" mul -> add_op
    | add "-" mul -> sub_op
    | mul
?mul: mul "*" prefix_expr -> mul_op
    | mul "/" prefix_expr -> div_op
    | mul "%" prefix_expr -> mod_op
    | prefix_expr
?prefix_expr: prefix* postfix_expr
?postfix_expr: atom postfix*
?atom: ident
     | integer
     | float
     | bool
     | string_concat
     | array
     | "(" expr ")"

postfix: "." ident -> get_attr
       | "[" (range | expr) "]" -> get_slice
       | "(" arg_list? ")" -> func_call

prefix: "+" -> prefix_plus
      | "-" -> prefix_neg
      | "~" -> prefix_binv
      | "!" -> prefix_not
      | "&" -> prefix_ref
      | "*" -> prefix_deref

bool: "true" -> bool_true
    | "false" -> bool_false

struct_field: ident ":" type ","

enum_field: ident ","

func_param_list: func_param ("," func_param)*
func_param: ident ":" ident

type: ident | array

fq_ident: (ident "::")* ident

!assign_op: "+=" -> plus_equal
          | "-=" -> minus_equal
          | "*=" -> times_equal
          | "/=" -> div_equal
          | "%=" -> mod_equal
          | "<<=" -> shl_equal
          | ">>=" -> shr_equal
          | "&=" -> bwand_equal
          | "|=" -> bwor_equal
          | "^=" -> bwxor_equal
          | "=" -> equal

range: range_start? ".." range_inclusive? range_end?
     | "[" range "]"
range_start: expr
range_end: expr
range_inclusive: "="
string_concat: STRING+
mut: "mut"
array: "[" ident ";" expr "]"
ident: /[A-Za-z_][A-Za-z0-9_]*/
float: FLOAT_NUMBER
integer: DEC_NUMBER | HEX_NUMBER | BIN_NUMBER | OCT_NUMBER

// await should probably be part of the expr rule
// AWAIT: "await"
STATIC: "static"
CONST: "const"

STRING: /([ubf]?r?|r[ubf])("(?!"").*?(?<!\\)(\\\\)*?"|'(?!'').*?(?<!\\)(\\\\)*?')/i

TRUE: "true"
FALSE: "false"
STRTYPE: "str"
BOOL: "bool"
F16: "f16"
F32: "f32"
F64: "f64"
I8: "i8"
I16: "i16"
I32: "i32"
I64: "i64"
U8: "u8"
U16: "u16"
U32: "u32"
U64: "u64"
CHAR: "char"
UNIT: "()"
IMPORT_ALL: "*"

%ignore /[\t \f\n]+/  // WS

_SPECIAL_DEC: "0".."9"        ("_"?  "0".."9"                       )*
DEC_NUMBER:   "1".."9"        ("_"?  "0".."9"                       )*
          |   "0"             ("_"?  "0"                            )* /(?![1-9])/
HEX_NUMBER.2: "0" ("x" | "X") ("_"? ("0".."9" | "a".."f" | "A".."F"))+
OCT_NUMBER.2: "0" ("o" | "O") ("_"?  "0".."7"                       )+
BIN_NUMBER.2: "0" ("b" | "B") ("_"?  "0".."1"                       )+

_EXP: ("e"|"E") ["+" | "-"] _SPECIAL_DEC
DECIMAL: "." _SPECIAL_DEC | _SPECIAL_DEC "." _SPECIAL_DEC?
FLOAT_NUMBER.2: _SPECIAL_DEC _EXP | DECIMAL _EXP?
// IMAG_NUMBER.2: (_SPECIAL_DEC      | FLOAT_NUMBER) ("J" | "j")
