
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'ASSIGN COLON COMMA DEFAULT ENUM F128 F32 F64 FN I128 I16 I32 I64 I8 IDENT IMPL IMPORT LANGLE LBRACE LPAREN RANGLE RARROW RBRACE RETURN RPAREN SEMI STRING STRUCT U128 U16 U32 U64 U8 UINT UNION\nsymbol_list : symbol_list symbol\n            | symbol\n\nsymbol : struct_decl\n       | enum_decl\n       | fn_decl\n       | default_decl\n       | impl_decl\n\nstruct_decl : STRUCT IDENT LBRACE field_list RBRACE\n\nenum_decl : ENUM IDENT LBRACE variant_list RBRACE\n\nvariant_list : variant_list variant\n             | variant\n\nvariant : IDENT\n\nfn_decl : FN IDENT LPAREN RPAREN RARROW IDENT LBRACE stmnt_list RBRACE\n       | FN IDENT LPAREN RPAREN LBRACE stmnt_list RBRACE\n\ndefault_decl : DEFAULT IDENT LBRACE RBRACE\n\nimpl_decl : IMPL IDENT LBRACE RBRACE\n\nstmnt_list : stmnt_list stmnt\n           | stmnt\n\nstmnt : abs_expr\n      | jump_expr\n\nabs_expr : literal SEMI\n         | IDENT ASSIGN IDENT SEMI\n         | IDENT ASSIGN literal SEMI\n\njump_expr : RETURN abs_expr SEMI\n\nliteral : UINT\n\nfield_list : field_list field\n           | field\n\nfield : IDENT COLON IDENT COMMA\n'
    
_lr_action_items = {'STRUCT':([0,1,2,3,4,5,6,7,13,31,32,34,36,53,61,],[8,8,-2,-3,-4,-5,-6,-7,-1,-15,-16,-8,-9,-14,-13,]),'ENUM':([0,1,2,3,4,5,6,7,13,31,32,34,36,53,61,],[9,9,-2,-3,-4,-5,-6,-7,-1,-15,-16,-8,-9,-14,-13,]),'FN':([0,1,2,3,4,5,6,7,13,31,32,34,36,53,61,],[10,10,-2,-3,-4,-5,-6,-7,-1,-15,-16,-8,-9,-14,-13,]),'DEFAULT':([0,1,2,3,4,5,6,7,13,31,32,34,36,53,61,],[11,11,-2,-3,-4,-5,-6,-7,-1,-15,-16,-8,-9,-14,-13,]),'IMPL':([0,1,2,3,4,5,6,7,13,31,32,34,36,53,61,],[12,12,-2,-3,-4,-5,-6,-7,-1,-15,-16,-8,-9,-14,-13,]),'$end':([1,2,3,4,5,6,7,13,31,32,34,36,53,61,],[0,-2,-3,-4,-5,-6,-7,-1,-15,-16,-8,-9,-14,-13,]),'IDENT':([8,9,10,11,12,19,20,25,26,27,28,29,33,35,37,38,39,43,44,45,46,48,50,51,52,54,55,57,60,62,63,],[14,15,16,17,18,24,27,24,-27,-12,27,-11,40,-26,-10,41,42,42,-18,-19,-20,42,-28,42,58,-17,-21,42,-24,-22,-23,]),'LBRACE':([14,15,17,18,30,41,],[19,20,22,23,39,51,]),'LPAREN':([16,],[21,]),'RPAREN':([21,],[30,]),'RBRACE':([22,23,25,26,27,28,29,35,37,43,44,45,46,50,54,55,57,60,62,63,],[31,32,34,-27,-12,36,-11,-26,-10,53,-18,-19,-20,-28,-17,-21,61,-24,-22,-23,]),'COLON':([24,],[33,]),'RARROW':([30,],[38,]),'RETURN':([39,43,44,45,46,51,54,55,57,60,62,63,],[48,48,-18,-19,-20,48,-17,-21,48,-24,-22,-23,]),'UINT':([39,43,44,45,46,48,51,52,54,55,57,60,62,63,],[49,49,-18,-19,-20,49,49,49,-17,-21,49,-24,-22,-23,]),'COMMA':([40,],[50,]),'ASSIGN':([42,],[52,]),'SEMI':([47,49,55,56,58,59,62,63,],[55,-25,-21,60,62,63,-22,-23,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'symbol_list':([0,],[1,]),'symbol':([0,1,],[2,13,]),'struct_decl':([0,1,],[3,3,]),'enum_decl':([0,1,],[4,4,]),'fn_decl':([0,1,],[5,5,]),'default_decl':([0,1,],[6,6,]),'impl_decl':([0,1,],[7,7,]),'field_list':([19,],[25,]),'field':([19,25,],[26,35,]),'variant_list':([20,],[28,]),'variant':([20,28,],[29,37,]),'stmnt_list':([39,51,],[43,57,]),'stmnt':([39,43,51,57,],[44,54,44,54,]),'abs_expr':([39,43,48,51,57,],[45,45,56,45,45,]),'jump_expr':([39,43,51,57,],[46,46,46,46,]),'literal':([39,43,48,51,52,57,],[47,47,47,47,59,47,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> symbol_list","S'",1,None,None,None),
  ('symbol_list -> symbol_list symbol','symbol_list',2,'p_symbol_list','parser.py',100),
  ('symbol_list -> symbol','symbol_list',1,'p_symbol_list','parser.py',101),
  ('symbol -> struct_decl','symbol',1,'p_symbol','parser.py',108),
  ('symbol -> enum_decl','symbol',1,'p_symbol','parser.py',109),
  ('symbol -> fn_decl','symbol',1,'p_symbol','parser.py',110),
  ('symbol -> default_decl','symbol',1,'p_symbol','parser.py',111),
  ('symbol -> impl_decl','symbol',1,'p_symbol','parser.py',112),
  ('struct_decl -> STRUCT IDENT LBRACE field_list RBRACE','struct_decl',5,'p_struct_decl','parser.py',119),
  ('enum_decl -> ENUM IDENT LBRACE variant_list RBRACE','enum_decl',5,'p_enum_decl','parser.py',126),
  ('variant_list -> variant_list variant','variant_list',2,'p_variant_list','parser.py',133),
  ('variant_list -> variant','variant_list',1,'p_variant_list','parser.py',134),
  ('variant -> IDENT','variant',1,'p_variant','parser.py',141),
  ('fn_decl -> FN IDENT LPAREN RPAREN RARROW IDENT LBRACE stmnt_list RBRACE','fn_decl',9,'p_fn_decl','parser.py',148),
  ('fn_decl -> FN IDENT LPAREN RPAREN LBRACE stmnt_list RBRACE','fn_decl',7,'p_fn_decl','parser.py',149),
  ('default_decl -> DEFAULT IDENT LBRACE RBRACE','default_decl',4,'p_declault_decl','parser.py',157),
  ('impl_decl -> IMPL IDENT LBRACE RBRACE','impl_decl',4,'p_impl_decl','parser.py',165),
  ('stmnt_list -> stmnt_list stmnt','stmnt_list',2,'p_stmnt_list','parser.py',172),
  ('stmnt_list -> stmnt','stmnt_list',1,'p_stmnt_list','parser.py',173),
  ('stmnt -> abs_expr','stmnt',1,'p_stmnt','parser.py',180),
  ('stmnt -> jump_expr','stmnt',1,'p_stmnt','parser.py',181),
  ('abs_expr -> literal SEMI','abs_expr',2,'p_abs_expr','parser.py',189),
  ('abs_expr -> IDENT ASSIGN IDENT SEMI','abs_expr',4,'p_abs_expr','parser.py',190),
  ('abs_expr -> IDENT ASSIGN literal SEMI','abs_expr',4,'p_abs_expr','parser.py',191),
  ('jump_expr -> RETURN abs_expr SEMI','jump_expr',3,'p_jump_expr','parser.py',198),
  ('literal -> UINT','literal',1,'p_literal','parser.py',205),
  ('field_list -> field_list field','field_list',2,'p_field_list','parser.py',212),
  ('field_list -> field','field_list',1,'p_field_list','parser.py',213),
  ('field -> IDENT COLON IDENT COMMA','field',4,'p_field','parser.py',223),
]
